MvcProje/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProje.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            var headingValues = headingManager.getList();
            return View(headingValues);
        }

        [HttpGet]
        public ActionResult addHeading()
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.getList() 
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            List<SelectListItem> valueWriter = (from x in writerManager.getList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName+ " "+ x.WriterLastName,
                                                    Value = x.WriterID.ToString()

                                                }).ToList();
                                              

            ViewBag.categoryName = valueCategory;
            ViewBag.writerName = valueWriter;
            return View();
        }

        [HttpPost]
        public ActionResult addHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            headingManager.add(heading);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.getList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();


            ViewBag.categoryName = valueCategory;
            var headingValue = headingManager.getByID(id);
            return View(headingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {

            headingManager.Update(heading);
            return RedirectToAction("Index");

        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = headingManager.getByID(id);
            
            if (headingValue.HeadingStatus)
            {
                headingValue.HeadingStatus = false;
            }
            else
            {
                headingValue.HeadingStatus = true;
            }
            headingManager.Delete(headingValue); 
            return RedirectToAction("Index");
        }



    }
}

MvcProje/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Başlık Düzenleme</h2>
<br />


@using(Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
<div class="form-group">

    @Html.Label("ID")
    @Html.TextAreaFor(x => x.HeadingID, new { @class = "form-control", @readonly = true})
    <br />
    @Html.Label("Başlık")
    @Html.TextAreaFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control", @readonly = true })
    <br />
    @Html.Label("Yazar Id")
    @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.categoryName,
                                            new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Kaydet</button>


</div>
}

MvcProje/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{  string color = "";
    string status = "";
    }


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Başlıklar </h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Oluşturulan Başlıklar</h3> 
                <div class="card-tools">
                    <a href="/Heading/addHeading" type="button" class="btn btn-success">Yeni Başlık Ekle</a> &nbsp;&nbsp;&nbsp;
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>

                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>
                            <th style="width: 25%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th><th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 15%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 30%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                        <tr>
                            <td>
                                @item.HeadingID
                            </td>

                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    @(((DateTime)item.HeadingDate).ToString("dd-MM-yyyy"))
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" title="@item.Writer.WriterName @item.Writer.WriterLastName" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td>
                                @switch (item.HeadingStatus)
                                {
                                    case true: status = "Aktif"; color = "badge badge-success"; break;
                                    case false: status = "Pasif"; color = "badge badge-danger"; break;
                                }
                                <span class="@color">@status</span>

                            </td>

                            <td class="project-state">
                                @switch (item.Category.CategoryName)
                                {
                                    case "Tiyatro": color = "badge badge-success"; break;
                                    case "Dizi": color = "badge badge-secondary"; break;
                                    case "Spor": color = "badge badge-primary"; break;
                                    case "Film": color = "badge badge-danger"; break;
                                    case "Kitap	": color = "badge badge-warning"; break;
                                }
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                    <i class="fas fa-folder">
                                    </i>
                                    Yazılar
                                </a>
                                <a class="btn btn-warning btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Güncelle
                                </a>
                                @if (item.HeadingStatus) { 
                                <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                    <i class="fas fa-trash">
                                    </i>
                                    Pasif Yap
                                </a>
                                }
                                @if (!item.HeadingStatus) { 
                                <a class="btn btn-success btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                    <i class="fas fa-check">
                                    </i>
                                    Aktif Yap
                                </a>
                                }
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->

        </div>
        <br />
       
        <br /><br />
        <!-- /.card -->
    </section>
</body>
</html>

MvcProje/Views/Heading/addHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "addHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<br />
<h2>Yeni Başlık Ekeleme</h2>
<br />


@using (Html.BeginForm("addHeading", "Heading", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName)
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.categoryName,
                                                          new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.writerName,
                                                          new { @class = "form-control" })
    <br />
    <br />

    <button class="btn btn-success">Kaydet</button>
</div>
}
<br />