MvcProje/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProje.Controllers
{
    public class WriterPanelContentController : Controller
    {
        // GET: WriterPanelContent
        ContentManager contentManager = new ContentManager(new EfContentDal());
        Context context = new Context();
        public ActionResult MyContent(string p)
        {
            
            p = (string)Session["WriterMail"];
            
            var writerIdInfo = context.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            
            var contentValues = contentManager.getListByWriter(writerIdInfo);
            return View(contentValues);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            content.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            
            string p = (string)Session["WriterMail"];
            var writerIdInfo = context.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            content.WriterID = writerIdInfo;
            content.ContentStatus = true;
            contentManager.add(content);
            return RedirectToAction("MyContent");
        }


    }
}

MvcProje/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
<div class="form-group">
    <input type="hidden" name="HeadingID" value="@ViewBag.d" />
    @Html.Label("Yazınız")
    @Html.TextAreaFor(x => x.ContentValue,4,30, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ContentValue)
    <br />
    
    <br />

    <button class="btn btn-success">Kaydet</button>
</div>}
<br />

MvcProje/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<br />
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="d-flex justify-content-center">
                </div>
                <br />
                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->

                        <div class="timeline">

                            @foreach (var item in Model)
                            {<!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MM-yyyy"))</span>
                                </div> <!-- /.timeline-label --> <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName </a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div> <!-- END timeline item -->}
                        </div>

                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>